### ISSUE TITLE
Failed at LinearConstraints.cpp:439

### ISSUE THREAD

**Issue by kx-guan** [jrl-umi3218/CaptureProblemSolver#1]
Hello,

About the paper "Capturability-based Analysis, Optimization and Control of 3D Bipedal Walking"(Stéphane Caron, Adrien Escande, Leonardo Lanari and Bastien Mallein,2018), I tried the code from your web, but got the following error messages:
```
 ....../CaptureProblemSolver/c++/src/LinearConstraints.cpp:439: void
 cps::LinearConstraints::performQPstep(Eigen::VectorXd&, const
 VectorXd&, bool*): Assertion `std::abs(Cp_[i]) > 1e-12' failed.
 Aborted (core dumped) 
```
Would you like to tell me the reason?
Thank you very much.

**Comment by stephane-caron** [comment]
This error seems related to a numerical-precision threshold setting that is too strict on your machine. I let @aescande point you to the proper parameter.

By "the code from your web", do you mean that you run the simulation from the [capture-walking](https://github.com/stephane-caron/capture-walking) repository? If so:

- Which scenario are you using? 
- Can you pull the latest commit, and then run 
```python
print controller.one_step.capture_pb
```
before the simulation step that fails?

**Comment by kx-guan** [comment]
Hi, Caron. Thank you very much.
  I downloaded the code from your web. Last time, I used the three kinds of scenarios, but in three cases, assertion failure occurred. 

  This time, I have tried to print the controller.one_step.capture_pb, the  messages that appeared just before assertion failure are as follows:

 delta = [0.010000000000000002, 0.030000000000000006, 0.04999999999999999, 0.07000000000000003, 0.08999999999999997, 0.10999999999999999, 0.12999999999999995, 0.1500000000000002, 0.16999999999999993, 0.18999999999999995];
g = 9.80664999999999942303929856279865;
init_omega_max = 4.42869055139326661674203933216631;
init_omega_min = 1.84989355867413318712522141140653;
init_zbar = 0.79899142452042615225593635841506;
init_zbar_deriv = 0.00021588206384534931324588324930;
lambda_max = 19.61329999999999884607859712559730;
lambda_min = 0.98066500000000000891731133378926;
s = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0];
target_height = 0.80000000000000004440892098500626;

 Also, I printed out the std::abs(Cp_[i] in the  439 line. The results are as follows:
   0.0234866
0.03904
0.0545287
0.0699684
0.0853748
0.100764
0.11615
0.13155
0.146978
0.76784
0.000207996
0.000654619
0.00129334
0.00207774
0.00296153
0.00389858
0.00484288
0.00574858
0.00657
0.0282553
1.72577e-07
5.33179e-07
1.04615e-06
1.68294e-06
2.41557e-06
3.21249e-06
4.03576e-06
4.83917e-06
5.56695e-06
2.35048e-05
9.89036e-13

 At last I commented out the 439 line, and recompiled. Nevertheless, the robot can walk in three scenarios.
  Thank you very much. Best regards.

**Comment by aescande** [comment]
Hi,

so this is indeed an issue of numerical thresholds.

The goal of this assert is to avoid dividing by 0 (or some number numerically equivalent to 0). In theory, division by 0 can not occur there, but since we are performing computations in finite-precision arithmetic, we want to make sure.

What happens here, and what I observed a few times before, is that either the SQP solver or the inner LS solver performs one too many iteration, that leads to a very small step in the LS, making `Cp_[i]` very small. I don't have the exact same numerical behavior as you for the problem you provide, but on my machine, the LS solver is making an additional iteration because the step is barely above the termination threshold, and I get a `CP_[i]` that, just like you, is barely under the assertion threshold.

A first fix would be to lower the threshold in the assert to `1e-13` or `1e-14`, but ideally, I should find a way to get a threshold that is adapted to each problem.
The second option is to change the parameter of the LS solver. We should probably offer a way to do it from the problem description file, but you can at least do it programmatically like this (in cpp):
```
auto lsp = solver.LSParameters();
lsp.minNorm_p(1e-9);
solver.LSParameters(lsp);
```
Setting the threshold for p to `1e-9` does the trick on my machine.
